### ISSUE TITLE
Is Slack Channel still active? 

### ISSUE THREAD

**Issue by SharedMocha** [letterpad/letterpad#134]
Welcome to Letterpad's GitHub repo! 👋🎉

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### To Reproduce

1.  This is the first step
2.  This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

-   Node Version:
-   Browser/OS:
-   Database:

**Comment by ajaxtown** [comment]
yes
