### ISSUE TITLE
Wrong login credential in the documentation

### ISSUE THREAD

**Issue by ronaldaug** [letterpad/letterpad#163]
### Issue Summary
Not really an issue, but document need to update.
I follow the installation guide [here](https://docs.letterpad.app/installation-and-setup/development#run)
and try to login admin but it always show "We couldnt find this email".
the actual initial credentials of admin are `demo@demo.com` & `demo`, **not** `admin@letterpad.com` & `demo`.

### Technical details:

-   Node Version: 12.7.0
-   Browser/OS: macOS - Mojave
-   Database: sqlite (default)

**Comment by ajaxtown** [comment]
Thanks. The docs are a little outdated. I will be updating it this weekend. Thanks for pointing this out.
