### ISSUE TITLE
Build a landing page

### ISSUE THREAD

**Issue by ajaxtown** [letterpad/letterpad#17]
### Story
Create a homepage (landing page) for letterpad.  This will be required for marketing purpose.

### Requirements
It should have the below links in the navigation menu.

- Docs (A link to documentation website)
- Features (Should scroll to the second section)
- Installation (Should scroll to the installation section)

The first section can be a banner with buttons/links pointing to github, twitter (@letterpad_cms). 

We will point 6 features with small dscriptions of each.

#### Speed
Letterpad is highly optimised for performance and follows all follows all best practices suggested by Google.

- Clean Interface
- SEO Friendly
- Open source
- React and GraphQL
- Editors (Markdown and Richtext)
- Minimal configuration

Use gh-pages to host this. We wil map it to our domain later.

**Comment by JPWallhorn** [comment]
Hey @ajaxtown, I will take over this one. I will create a separate repo for this and track the progress within that repo. Therefore, we will be able to close it out here and separate it from the actual CMS progress :)

**Comment by ajaxtown** [comment]
Perfect. And let me know when you finalize the template from themeforest and any other vendor, I will buy it for you.

**Comment by ajaxtown** [comment]
Done. https://letterpad.app
