### ISSUE TITLE
Error in graphql execution

### ISSUE THREAD

**Issue by NektariosFifes** [letterpad/letterpad#173]
Hello. My app works fine until i try to press "new" in the admin panel to create a now post or page.

This error is thrown in console:

`[debug]  resolvers/post.js:  Reached resolver: post
error.message : Cannot return null for non-nullable field Post.publishedAt.

[error]  api/server.ts:  Cannot return null for non-nullable field Post.publishedAt. { code: 'INTERNAL_SERVER_ERROR',
  exception:
   { stacktrace:
      [ 'Error: Cannot return null for non-nullable field Post.publishedAt.',
        '    at completeValue (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:560:13)',
        '    at completeValueCatchingError (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:495:19)',
        '    at resolveField (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:435:10)',
        '    at executeFields (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:275:18)',
        '    at collectAndExecuteSubfields (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:713:10)',
        '    at completeObjectValue (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:703:10)',
        '    at completeValue (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:591:12)',
        '    at /home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:492:16' ] } } { [GraphQLError: Cannot return null for non-nullable field Post.publishedAt.]
  message:
   'Cannot return null for non-nullable field Post.publishedAt.',
  locations: [ { line: 15, column: 3 } ],
  path: [ 'post', 'publishedAt' ],
  extensions:
   { code: 'INTERNAL_SERVER_ERROR',
     exception: { stacktrace: [Array] } } } {"message":"Cannot return null for non-nullable field Post.publishedAt.","locations":[{"line":15,"column":3}],"path":["post","publishedAt"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return null for non-nullable field Post.publishedAt.","    at completeValue (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:560:13)","    at completeValueCatchingError (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:495:19)","    at resolveField (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:435:10)","    at executeFields (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:591:12)","    at /home/nektarios-fifes/letterpad/node_modules/graphql/execution/execute.js:492:16"]}}}
`

**Comment by ajaxtown** [comment]
Yea this was as a part of the new update. Try this.

1. Do a git pull on letterpad. 
2. Run `yarn migrate`
3. Delete theme/hugo. 
4. Run `yarn install` on letterpad.

Or try a new install.

**Comment by NektariosFifes** [comment]
> Yea this was as a part of the new update. Try this.
> 
>     1. Do a git pull on letterpad.
> 
>     2. Run `yarn migrate`
> 
>     3. Delete theme/hugo.
> 
>     4. Run `yarn install` on letterpad.
> 
> 
> Or try a new install.

i still get the error

**Comment by ajaxtown** [comment]
Great.
