### ISSUE TITLE
More Unit Tests

### ISSUE THREAD

**Issue by abhisaha1** [letterpad/letterpad#18]
#### Story
We have some good amount of tests for covers the admin dashboard but it does not cover eveything. Write unit tests for majority of the components.

#### Requirements
You will find tests in `__tests__/admin.xxxx.js`. The admin tests should start with `test.`. You will get some idea on how we have covered tests.

To test the unit test, use the command `yarn test [testname]`

**Comment by tienpham94** [comment]
This is up for grabs in case anyone interested, I will be focusing on other things.
