### ISSUE TITLE
The slack invite link doesn't work.

### ISSUE THREAD

**Issue by shackhorn** [letterpad/letterpad#200]
the slack invite link does not work.

**Comment by ajaxtown** [comment]
I do see its working. Can you try this link - https://join.slack.com/t/letterpad/shared_invite/zt-4vcma4ac-HUFO~9rYaerc1jFxM7U_7A

**Comment by shackhorn** [comment]
That link works, however, the invite link on the README.md in the main repository doesn't seem to work.

**Comment by ajaxtown** [comment]
Please use this link - https://tinyurl.com/letterpad-invite
