### ISSUE TITLE
Enhance the editor

### ISSUE THREAD

**Issue by ajaxtown** [letterpad/letterpad#23]
#### Story
The editor of letterpad has everything required. However, we would like to change the editor with more clean UI, specially the rich text editor.

#### Requirements
It should all the features that we currently have. Whatever we can do with markdown, we should have exactly those features. 

Which library can we use which has the simplicity of the medium editor as well as can be used for markdown ?

**Comment by aiupjulian** [comment]
Perhaps [Draft.js](https://github.com/facebook/draft-js) could be useful?
You can install [plugins](https://github.com/draft-js-plugins/draft-js-plugins) too.
[Here is an article](https://medium.com/@rajaraodv/why-draft-js-and-why-you-should-contribute-460c4a69e6c8) explaining it.
If you want I can contribute and try to implement it.

**Comment by ajaxtown** [comment]
Yes, we thought of `draft.js` but the api is a little complex for everyone to contribute. `slate.js` comes from draft.js. It has a much more flexible API and the plugin system is easy as compared to draft. I see you have joined  Slack. I have addd you in the dev channel. Thanks!

**Comment by ajaxtown** [comment]
We decided to go with `slate.js`. 
This is being taken care here - https://github.com/letterpad/letterpad/pull/73
