### ISSUE TITLE
Should comments be internal feature ?

### ISSUE THREAD

**Issue by abhisaha1** [letterpad/letterpad#279]
Comments is still a question for us. Maintaining comments will be super difficult if we decide to build it internally. Comment Integration can be done with Disqus (which we had previously) and but removed because we felt it was too commercial. 
Now that letterpad is a platform, it does make sense to have our own commenting app as well. 

Thoughts ?

**Comment by acudroit** [comment]
(Basically there are already other ways to add comments, there's no need for a direct implementation) and assuming that the blogger will post their link on a social platform they will just simply receive comments from said platform that they promoted their link on

**Comment by acudroit** [comment]
Comments also opens up a scope for potential XSS issues or for API security issues

**Comment by acudroit** [comment]
The objective here is to keep this platform good while *minimizing* attack surfaces, if we start for example adding a bunch of add-ons bullcrap or whatever like wordpress then that would be creating more attack surfaces, if we start adding comments then more potential for injection attacks, all the readers should be doing is reading the content, not being allowed to inject or put anything anywhere on the page

**Comment by acudroit** [comment]
Focus on keeping the bloggers account secure and focus on keeping your API endpoints secure, go through every logic process of this platform and make sure that from a coding standpoint that there won't be a logic faulty issue, make sure everything is going to behave how it *should* behave and whatever libraries you're using or language just make sure to keep everything updated and search for secure practices, vulnerabilities relating to vendors, etc, etc

**Comment by gorkemcetin** [comment]
Currently I see that an open source commenting library is used for this purpose, however it requires Github login which defies the purpose of building a blogging platform that can also cover those who don't have a Github account and/or don't want to open one. It may be turning off for many people just to see that they have to open another account to be able to comment a 1-liner.

**Comment by abhisaha1** [comment]
Because Letterpad now has community around it, internal comments are essential for more engagement. This is already released.
