### ISSUE TITLE
Media uploading is broken

### ISSUE THREAD

**Issue by alder** [letterpad/letterpad#28]
### Issue Summary

User couldn't see new images on the Media page after uploading.

### Steps To Reproduce

1.  Login to Admin dashboard as demo user
2.  Go to Media page
3.  Press 'Add media'
4.  Select some JPG file and upload it

**ER**: User should see new media card on the Media page.
**AR**: User doesn't see uploaded image.

Image successfully uploaded and user can find it in ```public/uploads``` directory, but in database table ```media``` there are ```NULL``` value for this image in ```author_id``` column.

![image](https://user-images.githubusercontent.com/199887/41743352-cd48be58-75a0-11e8-963a-dbbf48d1f105.png)

### Technical details:

-   Node Version: v8.1.3
-   Browser/OS: FF 60.0.2 (64-bit) / Ubuntu 18.04
-   Database: sqlite

**Comment by ajaxtown** [comment]
Thanks @alder for reporting this issue. I have started working on additional features of the media gallery. I create a hotfix for this now.

**Comment by ajaxtown** [comment]
@alder, can you pull from master and this is again please ?

**Comment by alder** [comment]
It works now. Thanks!

I have a question about image resizing, but it should be other ticket. This issue resolved and can be closed.
