### ISSUE TITLE
Invalid link 'View your site' in Getting Started section 

### ISSUE THREAD

**Issue by alder** [letterpad/letterpad#29]
### Issue Summary

Invalid link 'View your site' in Getting Started section 

### Steps To Reproduce

1.  Login to Admin dashboard as demo user
2.  Click link 'View your site' in Getting Started section

**ER:** User should see site home page opened.
**AR:** User sees 'Write a blog post' page opened.

### Technical details:

-   Node Version: v8.1.3
-   Browser/OS: FF 60.0.2 (64-bit) / Ubuntu 18.04
-   Database: sqlite

**Comment by alder** [comment]
@ajaxtown something strange. Now link is correct, but when I try to click I sees white page. Can you check this?

**Comment by ajaxtown** [comment]
Thanks @alder - I have added `target="_blank"` to this. Its in this PR https://github.com/letterpad/letterpad/pull/32

This is a big PR and I have done changes related to how the models are connected to database. I have done a rough check and everything seems to be ok. But it will be nice if you can test this branch a bit before I merge.

**Comment by ajaxtown** [comment]
I tested this a bit more and with fair amount fo confidence merged the branch.

**Comment by alder** [comment]
Sorry, missed your comments.
I will fetch new version and provide additional checks :)
