### ISSUE TITLE
Dark dropdown box appears while adding tags in light theme.

### ISSUE THREAD

**Issue by spiritualcrisis** [letterpad/letterpad#317]
Welcome to Letterpad's GitHub repo! 👋🎉

### Issue Summary

While adding tags dropdown box has a background of black.
![image](https://user-images.githubusercontent.com/21973492/161444166-c779b741-ff64-41b9-8f00-6c4427a738a1.png)

### To Reproduce

1.  Switch to light theme
2.  Try adding a Tag to your post

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

NA

**Comment by abhisaha1** [comment]
Fixed
