### ISSUE TITLE
Feature Request : No Option to resize or crop Images added from any medium

### ISSUE THREAD

**Issue by spiritualcrisis** [letterpad/letterpad#318]
### Issue Summary

Add a feature to resize/crop images in order to manage images on the blog.

**Comment by abhisaha1** [comment]
Follow this PR - https://github.com/letterpad/letterpad/pull/329

**Comment by abhisaha1** [comment]
Crop option is not possible since it will bring additional complexities and can affect unsplash images. Resize option has been added.
