### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by acudroit** [letterpad/letterpad#376]
![Screenshot_20220712-005629](https://user-images.githubusercontent.com/95527097/178570348-860e8480-833b-4c56-a322-861c3cb9543c.jpg)
![Screenshot_20220712-005733__01](https://user-images.githubusercontent.com/95527097/178570367-6b5df47e-1bc4-4096-966f-0144e3d6a6aa.jpg)

**Comment by abhisaha1** [comment]
This has been fixed.
