### ISSUE TITLE
Post status switcher is broken

### ISSUE THREAD

**Issue by alder** [letterpad/letterpad#39]
### Issue Summary

Draft/publish switcher is broken.

### Steps To Reproduce

1.  Login to Admin dashboard as demo user
2.  Go to Posts page
3.  Open some post for edit or create new post
4.  Try to change post status

**ER:** Post status should be changed.
**AR:** Nothing happens.

Possible this issue happens with my React version - 16.4.1.

### Technical details:

-   Node Version: v10.5.0
-   Browser/OS: FF 60.0.2 (64-bit) / Ubuntu 18.04
-   Database: sqlite

**Comment by ajaxtown** [comment]
Thanks @alder. I see you are using node `v10.5`. Someone else tried to use the node `v10+` and sqlite  didn't work properly. Did you face any problem with sqlite, mainly in seeding/migrations.

**Comment by alder** [comment]
This issue also happens with node ```v.8.1.3``` and I tried to update version for possible fix. But this didn't help. And there are no issues with migrations/seeding the database for me.

Possible  there a issue with ```getDerivedStateFromProps(nextProps, prevState)``` for ```PostPublish``` component - https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by ajaxtown** [comment]
Thanks @alder - I am taking a look at this.
