### ISSUE TITLE
Database migrations failed

### ISSUE THREAD

**Issue by alder** [letterpad/letterpad#44]
### Issue Summary

When user try to install/update Letterpad from master branch database migrations failed.

### To Reproduce

1.  Clone letterpad repository
2.  Run ```yarn install```

There are 2 issues with migrations:
1.  Settings table is now called ```setting``` instead of ```settings```
2.  Sequelize addColumn() doesn't check if column already exists and addMediaInfoFields migration fails.

### Technical details:

-   Node Version: v10.5.0
-   Browser/OS: FF 60.0.2 (64-bit) / Ubuntu 18.04
-   Database: sqlite

**Comment by ajaxtown** [comment]
Oh yes. The migrations contain the table settings and it should be setting. I changed the table name, forgot to change the migration files. my bad.

**Comment by alder** [comment]
@ajaxtown please, review my PR with fixes.
