### ISSUE TITLE
Left hand menu items not aligned

### ISSUE THREAD

**Issue by gorkemcetin** [letterpad/letterpad#487]
Left hand menu items are not aligned. I am using 4.0.1 version on Brave browser. Please see a screenshot attached. 
<img width="237" alt="Screen Shot 2023-01-14 at 11 50 05 AM" src="https://user-images.githubusercontent.com/1191477/212485172-c3df46a0-8485-4abd-a179-683f108e6122.png">

**Comment by abhisaha1** [comment]
Thanks @gorkemcetin  for reporting.

**Comment by abhisaha1** [comment]
Fixed in https://github.com/letterpad/letterpad/pull/490
