### ISSUE TITLE
Suggestions for Letterpad

### ISSUE THREAD

**Issue by gorkemcetin** [letterpad/letterpad#488]
I have been using Letterpad for some time and loving it. I have a few suggestions on my way to embracing this software, so here they are. 

*Editor*

The editor could be improved. Not saying the main editor should be changed from TinyMCE, but the way the editing "onboarding" process could be improved. For example: 

* Both the title and (IMHO a necessity but the author can set it optional subtitle) placeholders should be there and the placeholder font colors could be subtler.
* When a new page is created, the cursor pointer should be on the main title so that the author knows where to start.
* There could be a better way to implement the cover image (e.g directly drag-dropping a cover image towards the beginning of the editor) 
* When I go to a new paragraph, editor buttons appear. This may confuse and distract the user (at least this is what happened in my case). 

*Settings*

* The page looks good and feels tidy. There may be an option to separate the settings menus to another menu on the left hand side of the page. 
* The location of the additional scripts is unclear. 

*UX/UI related*

* When I try to publish a page, it gives me a warning that it is not linked, and not visible. The style of this popup is not on par with the rest (modals).
* The author shouldn't be able to edit the /page section, e.g this word needs to be non-modifiable. 
* When I have a good number of posts, I would like to know how many posts are there, how many of them are draft and how many are published.

*Possible bugs*

* When I rename a tag, nothing happens (popup doesn't go away and there is no feedback). Probably a bug and I can report if that is the case. 
* When I go to tags and remove a tag, and then go to posts, I see that tag still on the page. The page should be synced so that the tags shouldn't be there anymore. 

*Other*

* I would like to see total posts that is referred by a tag, under Tags.
* Each popup should be discarded by ESC key.

**Comment by abhisaha1** [comment]
Hello @gorkemcetin, thank you for the suggestions. Those are great points. I am on vacation and will be back in 4 days. Will get back to this after I am back.

**Comment by abhisaha1** [comment]
> Settings
The page looks good and feels tidy. There may be an option to separate the settings menus to another menu on the left hand side of the page.
The location of the additional scripts is unclear.

It was like the way you mentioned before and the setting was collapsible. I changed it reduce the size of the left side menu and also reduce complexity. However, quick accessibility is a problem. We also have to consider that in future, this can increase. I will think a bit on this.

**Comment by abhisaha1** [comment]
@gorkemcetin I have worked on few of the issues/improvements on this PR - https://github.com/letterpad/letterpad/pull/490 
The second part of the PR will be related to Editor improvements. Thanks again for taking the time in writing down these suggestions.

**Comment by abhisaha1** [comment]
@gorkemcetin could you please create separate issues for the below suggestions you mentioned - 

> - When I go to a new paragraph, editor buttons appear. This may confuse and distract the user (at least this is what happened in my case).

(This one is a bit challenging. I am afraid this cannot be taken care anytime soon.)

_Settings_

> - The page looks good and feels tidy. There may be an option to separate the settings menus to another menu on the left hand side of the page.
> - The location of the additional scripts is unclear.

_Others_

> - I would like to see total posts that is referred by a tag, under Tags.

Could you explain a bit more on this. Currently it shows the posts count beside each tag under tags. 


Rest of the suggestions/bugs you mentioned are live.

**Comment by gorkemcetin** [comment]
> Could you explain a bit more on this. Currently it shows the posts count beside each tag under tags.

I think I have missed this, so you can ignore my suggestion.

**Comment by abhisaha1** [comment]
Closing this as all issues are resolved. Thanks @gorkemcetin
