### ISSUE TITLE
Logo contribution for letterpad

### ISSUE THREAD

**Issue by reallinfo** [letterpad/letterpad#49]
Hello!

I designed a logo for letterpad. I think I designed a logo that is compatible with the function of the application. What do you think? If you want it, i will send a pr. Logo idea is available below.

![letterpad](https://user-images.githubusercontent.com/36298335/41813396-27bac8ec-773e-11e8-8ed9-d2bb1c4e9f77.jpg)

**Comment by ajaxtown** [comment]
This is epic. I cannot agree more. Thank you.

**Comment by ajaxtown** [comment]
Please send a PR with relevant assets.

**Comment by reallinfo** [comment]
I customize the logo slightly and i sen a pr.

Also, i updated the readme file. Please check it.

https://github.com/letterpad/letterpad/pull/50

**Comment by ajaxtown** [comment]
@reallinfo please share your twitter username.

**Comment by ajaxtown** [comment]
Also, could you also have another version wehre LP is square. In github and slack, they require a square logo.

**Comment by reallinfo** [comment]
Thank you very much but i don't use the twitter. Here are the square version; How is that? which one do you prefer?


![2](https://user-images.githubusercontent.com/36298335/41868193-01389f2e-78be-11e8-820f-2030b5989641.jpg)
