### ISSUE TITLE
Posts page small UX issue

### ISSUE THREAD

**Issue by gorkemcetin** [letterpad/letterpad#496]
I believe the posts page (which is the most important area of LetterPad after the editor) can be improved a bit to increase UX. I have written down the explanation for the small issue I see directly on the image below.

<img width="947" alt="Better user experience" src="https://user-images.githubusercontent.com/1191477/213931913-f5f7095d-fef3-4ba8-8bd3-40377dc9db4f.png">

Also can you increase the width of "All Tags"? On my browser it almost overflows the button as can be seen here. I should have opened another issue for this but so lazy to do it :-)

<img width="273" alt="Screen Shot 2023-01-22 at 12 59 15 PM" src="https://user-images.githubusercontent.com/1191477/213932034-5e694ecc-db17-46c4-99c6-f56c1c6853d6.png">

**Comment by abhisaha1** [comment]
Fixed https://github.com/letterpad/letterpad/pull/498

Regarding the second point that you mentioned, the problem still exist. I will replace the select dropdown in few days as it effects all dropdowns.

Closing this issue.
