### ISSUE TITLE
Newsletter subscription button doesn't work

### ISSUE THREAD

**Issue by gorkemcetin** [letterpad/letterpad#497]
I tried to subscribe to the newsletter, however clicking the button doesn't work and it throws this error on the console: 

**Uncaught (in promise) SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON**

<img width="431" alt="Screen Shot 2023-01-22 at 1 03 46 PM" src="https://user-images.githubusercontent.com/1191477/213932292-c94ded38-6fb7-4080-b085-d964beaff0cd.png">

**Comment by ashish-khankari** [comment]
Assign me this task

**Comment by abhisaha1** [comment]
This is fixed.
