### ISSUE TITLE
Customising Homepage of a blog 

### ISSUE THREAD

**Issue by abhisaha1** [letterpad/letterpad#520]
The Homepage can be a page or a collection of posts. Most of the blogs (almost all) choose a collection of posts which they can group with the help of a tag.

As a theme developer, my choices to create a homepage with a collection of posts is very limited. What would increase the choices and design thinking can be:

- Having multiple collections of posts. 
- Introducing category. Any tag which starts with `_` will be considered as category. 
- Latest Posts, Featured Posts, Most Popular posts ? How can we achieve the last 2 ?

## Design
- Not all themes are going to respect this. Minimal themes will stay minimal.
- How to let users know that each theme are different, few might not show the banner, few might not respect all the settings that gets applied in dashboard.

I am looking for ideas on how to create various designs for homepage. And this can only happen, if from dashboard we provide more granular way to group posts.

**Comment by gorkemcetin** [comment]
A question (halfway related to the issue) - do themes honor homepage layout (e.g magazine/grid/stacked) etc?

**Comment by abhisaha1** [comment]
Every theme can have its own layout. Every theme will display posts in chronological order. But each theme can house posts from other tags. 

Currently which other tags can the theme choose cannot be controlled.

**Comment by abhisaha1** [comment]
One way to tackle this by having settings for each theme.

**Comment by gorkemcetin** [comment]
OK here are my suggestions for each theme configuration: 

This is how theme homepage layout and fonts would look like:

<img width="709" alt="Screen Shot 2023-03-12 at 2 14 36 PM" src="https://user-images.githubusercontent.com/1191477/224564160-ba056916-77db-45c9-b4cc-3fb2e2cd06a9.png">

If theme allows, a top cover (header image) can also be configured: 

<img width="816" alt="Screen Shot 2023-03-12 at 2 14 56 PM" src="https://user-images.githubusercontent.com/1191477/224564212-fbe7c03f-e9e6-45c9-a802-4ee9f13590fc.png">

If theme allows, header and footer menus can be placed as well: 

<img width="829" alt="Screen Shot 2023-03-12 at 2 17 06 PM" src="https://user-images.githubusercontent.com/1191477/224564269-a06a32a1-4977-49b7-947c-448f96ac3415.png">

**Comment by abhisaha1** [comment]
This is a very intuitive design. Thanks for sharing. 

As a theme developer, if I want to give an additional setting, I will have to change the admin settings. This is not very scalable.

**Comment by gorkemcetin** [comment]
Understood, thought the same as well.

**Comment by abhisaha1** [comment]
It is not possible to add themes. I think your design is more maintainable. I want to rename themes to layouts. That way, I can provide some level of customisations. But themes are hard to maintain and I am skipping this idea.
