### ISSUE TITLE
User can't assign additional existing category/tag to post

### ISSUE THREAD

**Issue by alder** [letterpad/letterpad#53]
### Issue Summary

User can't select more than 1 existing category/tag for post. Suggestions works correctly.

### Steps To Reproduce

1.  Login to Admin dashboard as demo user
2.  Go to Posts page
3.  Edit some post
4.  Try to assign additional existing category/tag to this post

**ER:** Tag/Category should be successfully added.
**AR:** Client raises an error:

![image](https://user-images.githubusercontent.com/199887/41874152-5370f648-78c7-11e8-8f59-cc8c07f64945.png)

For taxonomies we use ```name``` field to store the tag/category, but ReactTags library wants ```text``` field.

### Technical details:

-   Node Version: v10.5.0
-   Browser/OS: FF 60.0.2 (64-bit) / Ubuntu 18.04
-   Database: sqlite

**Comment by ajaxtown** [comment]
Issue fixed
