### ISSUE TITLE
Account Creation with Email Fails

### ISSUE THREAD

**Issue by jaruba** [letterpad/letterpad#537]
### Issue Summary

When trying to create an account with email + password it fails (no visible error in the UI, but I attached an image with the error from dev tools).

<img width="1365" alt="Screenshot 2023-07-09 at 18 00 27" src="https://github.com/letterpad/letterpad/assets/1777923/0ed3202b-0f19-4f81-b30b-8d3d65f58814">

### To Reproduce

1.  Go to https://letterpad.app/admin/register
2. Enter email and password
3. Press "Register"

### Technical details:

- Node Version: N/A
- Browser/OS: N/A
- Database: N/A

**Comment by abhisaha1** [comment]
Thanks for reporting this. I will fix it.

**Comment by abhisaha1** [comment]
Fixed
