### ISSUE TITLE
Drafts are invisible

### ISSUE THREAD

**Issue by ianquill** [letterpad/letterpad#561]
### Issue Summary

Drafts aren't showing up after creation?
letterpad.app/posts lists 5 drafts (previously worked on) but says 'no records found'. Clicking the drafts button to filter does nothing. 

Creating a new draft and saving it will add 1 more draft to the number of total drafts, but still show 'no records found'. 
![Screenshot 2023-09-06 at 07-57-04 Letterpad - A free blog publishing platform](https://github.com/letterpad/letterpad/assets/65085764/20b7b567-7bef-4f12-b072-3eec53390b18)

### Technical details:

letterpad.app
Firefox
Windows 11

**Comment by abhisaha1** [comment]
Thanks @ianquill for reporting. Sorry about this, I am working on blog post history and added a wrong condition which led to this bug. Fixed it yesterday.
