### ISSUE TITLE
bug: Sign in with Github results in a 404

### ISSUE THREAD

**Issue by NBK-01** [letterpad/letterpad#606]
### Issue Summary

Creating a new account with the Github SSO redirects user to 404 | Not found page

### To Reproduce

1. Click the get started for free CTA on the landing page as a new user
2. Go to "sign in with github"

This is on the deployed version, not local

**Comment by abhisaha1** [comment]
Thanks @NBK-01 for reporting.

**Comment by abhisaha1** [comment]
Fixed.
