### ISSUE TITLE
bug: text cut off on settings dashboard

### ISSUE THREAD

**Issue by NBK-01** [letterpad/letterpad#607]
### Issue Summary

Text containers on some settings sections cut off on different screen sizes or are just a bit too long

<img width="1191" alt="Screenshot 2024-01-11 at 2 01 56 PM" src="https://github.com/letterpad/letterpad/assets/73779089/ba85709a-c560-4cdf-afce-7fc9521ef515">

<img width="1192" alt="Screenshot 2024-01-11 at 2 02 11 PM" src="https://github.com/letterpad/letterpad/assets/73779089/672af03c-e118-4627-b24d-a301fbaea69e">

**Comment by NBK-01** [comment]
This is minor but thought you should know. I would love work on some issues but unfortunately can't right now.

**Comment by abhisaha1** [comment]
Thank you. I will fix it.

**Comment by abhisaha1** [comment]
@NBK-01 could you tell me how to reproduce this issue? Which operating system and which browser and resolution?

**Comment by NBK-01** [comment]
@abhisaha1 Using both Arc and Brave on a Mac M2.  

The settings page: the delete account tab + openAi key tab

Uploading Screen Recording 2024-01-23 at 12.49.04 PM.mov…

**Comment by abhisaha1** [comment]
Fixed.
