### ISSUE TITLE
Changing post topic adds a new topic to the post instead of replacing the previously assigned topic

### ISSUE THREAD

**Issue by lucasfugisawa** [letterpad/letterpad#623]
### Issue Summary

Changing the post topic adds a new topic to the post instead of replacing the previously assigned topic

### To Reproduce

1.  Create a post.
2. In the post Settings screen, set the post Topic.
3. Save / publish the post.
4. Go to the post Settings screen again and change the Topic to another one.
5. Go to Posts (posts list) screen and check the post "Tags" column. 

### Why do you consider this to be a bug? What did you expect to happen instead?
The "Topic" drop-down menu does not allow multiple selections. The "Topic" attribute seems to be designed to allow a single category selection.

### Technical details:

- Browser: Google Chrome Version 121.0.6167.162 (Official Build) (64-bit).
- OS: Windows 11 Pro Version 23H2 Build 22631.3155 with Windows Feature Experience Pack 1000.22684.1000.0.

<img width="1915" alt="letterpad post topic selection bug" src="https://github.com/letterpad/letterpad/assets/2525178/90e5edd9-8240-4d05-aafe-e0ffe3c696b9">

**Comment by abhisaha1** [comment]
Thanks @lucasfugisawa. Fixed!

**Comment by lucasfugisawa** [comment]
Thank you, @abhisaha1!
