### ISSUE TITLE
Sort "Topic" drop-down options alphabetically

### ISSUE THREAD

**Issue by lucasfugisawa** [letterpad/letterpad#628]
### Feature Enhancement Summary

Sort "Topic" drop-down options alphabetically to enhance usability.

### To Reproduce

1. Create a post.
2. In the post Settings screen, click the Topic drop-down.
<img width="1414" alt="letterpad-sort-dropdown-suggestion" src="https://github.com/letterpad/letterpad/assets/2525178/8c8b2ae4-ef2f-49ea-8ba5-4a118e13138b">

### Additional suggestion: 
Review if other drop-down fields should have the values sorted too.

**Comment by abhisaha1** [comment]
Fixed. Thanks @lucasfugisawa
