### ISSUE TITLE
NOTICE: Rebasing master (reduce git clone size)

### ISSUE THREAD

**Issue by boopathi** [letterpad/letterpad#65]
The `git clone` of the project is huge (~100MB) and contains some unnecessary files (generated ones) in the git history. I cleaned it up and now have a master branch that is ~7MB. I removed the following files from all commits of the git history of master.

* `*.min.js` and `*.map` files
* generated css files
* sqlite content (db_log files, ibdata* files, etc...)
* sql files

I'll **force push** to master today and update the status here.

**STATUS: DONE**

If you're working on something in a branch, it's **NOT** possible to rebase it to master once I push the new commits. Please follow the below instructions to help you easily move your work and rebase it with current master.

At the time of this writing, there are 2 PRs and I'll manually update them using the following steps. 

1. Commit your work in your current branch (say `my-feature`)
1. Switch to master - `git checkout master`
1. Create a copy of the old master and delete `master`.
   * `git checkout -b old-master`
   * `git branch -D master`
1. Fetch the changes - `git fetch`
1. Create the new master
   * `git checkout -b master origin/master`
1. Verify you're in the right branch
   * In the top-level there should be an empty file called `new-master`.
1. Checkout a new branch from the new master
   * `git checkout -b my-feature-1`
1. Cherry-pick the commits from your branch `my-feature` into `my-feature-1`.
   * Checkout into your old branch: `git checkout my-feature`
   * `git log` to print the log and note (copy into a file) the hashes of the commit you want to pick
   * Checkout into your new branch: `git checkout my-feature-1`
   * `git cherry-pick my-commit-hash` (replace `my-commit-hash` with the commit hash you copied from the previous step. Repeat cherry-pick in the order of the commits.

Other method (don't preserve commits in your branch):

1. Commit your work in your current branch (say `my-feature`)
1. Create a patch for your branch: `git diff master > my-feature.patch`
1. Switch to master - `git checkout master`
1. Create a copy of the old master and delete `master`.
   * `git checkout -b old-master`
   * `git branch -D master`
1. Fetch the changes - `git fetch`
1. Create the new master
   * `git checkout -b master origin/master`
1. Verify you're in the right branch
   * In the top-level there should be an empty file called `new-master`.
1. Checkout a new branch from the new master
   * `git checkout -b my-feature-1`
1. Apply the patch to your new branch
   * `git apply my-feature.patch`
1. Commit the changes
   * `git commit`

**Comment by ajaxtown** [comment]
Done
